

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "XFramework.T4Generator\App.config"
//     Connection String Name: "FlexFrameDB"
//     Connection String:      "Data Source=TNA-8ZTPG82;Initial Catalog=Orion_Sprint14_QA;Persist Security Info=True;User ID=sa;password=**zapped**;;MultipleActiveResultSets=True;Application Name=EntityFramework"
// ------------------------------------------------------------------------------------------------


namespace XFramework.Models
{

}


